FROM rust:1.71 AS build
WORKDIR /app
COPY ./core .
RUN cargo build --release

FROM debian:bookworm-slim
COPY --from=build /app/target/release/ap1_core /usr/local/bin/ap1_core
WORKDIR /app
CMD ["/usr/local/bin/ap1_core"]
